# DataCamp: Supervised Learning with Scikit Learn

## Chapter 2 - Introduction to Regression

Supervised Classification problem: Using labeled financial data to predict whether the value of a stock will go up or go down next week.

x: [Predictor, Independent, Features]

y: [Response, Dependent, Target] 

## Introduction to Regression

### Importing data for supervised learning

In this chapter, you will work with Gapminder (https://www.gapminder.org/data/) data that we have consolidated into one CSV file available in the workspace as 'gapminder.csv'. Specifically, your goal will be to use this data to predict the life expectancy in a given country based on features such as the country's GDP, fertility rate, and population. As in Chapter 1, the dataset has been preprocessed.

Since the target variable here is quantitative, this is a regression problem. To begin, you will fit a linear regression with just one feature: 'fertility', which is the average number of children a woman in a given country gives birth to. In later exercises, you will use all the features to build regression models.

Before that, however, you need to import the data and get it into the form needed by scikit-learn. This involves creating feature and target variable arrays. Furthermore, since you are going to use only one feature to begin with, you need to do some reshaping using NumPy's .reshape() method. Don't worry too much about this reshaping right now, but it is something you will have to do occasionally when working with scikit-learn so it is useful to practice.

In [ ]:
# Import numpy and pandas
import numpy as np
import pandas as pd

# Read the CSV file into a DataFrame: df
df = pd.read_csv('gapminder.csv')

df.head()

#    population  --fertility--  HIV        CO2  BMI_male      GDP  BMI_female  --life--  \
# 0  34811059.0       2.73      0.1   3.328945  24.59620  12314.0    129.9049    75.3   
# 1  19842251.0       6.43      2.0   1.474353  22.25083   7103.0    130.1247    58.3   
# 2  40381860.0       2.24      0.5   4.785170  27.50170  14646.0    118.8915    75.5   
# 3   2975029.0       1.40      0.1   1.804106  25.35542   7383.0    132.8108    72.5   
# 4  21370348.0       1.96      0.1  18.016313  27.56373  41312.0    117.3755    81.5   

#    child_mortality  
# 0             29.5  
# 1            192.0  
# 2             15.4  
# 3             20.0  
# 4              5.2

# Create arrays for features and target variable
y = df['life'].values
X = df['fertility'].values

print(X)
# [ 2.73  6.43  2.24  1.4   1.96  1.41 ... 2.11  2.46  1.86  5.88  3.85]

X.shape
# Out[6]: (139,)

print(y)
# [ 75.3  58.3  75.5  72.5  81.5  80.4  70.6 ...  76.   68.7  75.4  52.   49. ]

y.shape
# Out[5]: (139,)

# Print the dimensions of X and y before reshaping
print("Dimensions of y before reshaping: {}".format(y.shape))
print("Dimensions of X before reshaping: {}".format(X.shape))

# Reshape X and y 
y = y.reshape(-1, 1)
X = X.reshape(-1, 1)

# Print the dimensions of X and y after reshaping
print("Dimensions of y after reshaping: {}".format(y.shape))
print("Dimensions of X after reshaping: {}".format(X.shape))

# Print the dimensions of X and y before reshaping
print("Dimensions of y before reshaping: {}".format(y.shape))
print("Dimensions of X before reshaping: {}".format(X.shape))

# Dimensions of y before reshaping: (139,)
# Dimensions of X before reshaping: (139,)
# Dimensions of y after reshaping: (139, 1)
# Dimensions of X after reshaping: (139, 1)
    
print(y)
# [[ 75.3]
#  [ 58.3]
#  [ 75.5]
# ...
#  [ 75.4]
#  [ 52. ]
#  [ 49. ]]

print(X)
# [[ 2.73]
#  [ 6.43]
#  [ 2.24]
#  [ 1.4 ]
#  ...
#  [ 2.46]
#  [ 1.86]
#  [ 5.88]
#  [ 3.85]]


## Exploring the Gapminder data

As always, it is important to explore your data before building models. On the right, we have constructed a heatmap showing the correlation between the different features of the Gapminder dataset, which has been pre-loaded into a DataFrame as df and is available for exploration in the IPython Shell. Cells that are in green show positive correlation, while cells that are in red show negative correlation. Take a moment to explore this: Which features are positively correlated with life, and which ones are negatively correlated? Does this match your intuition?

Then, in the IPython Shell, explore the DataFrame using pandas methods such as .info(), .describe(), .head().

In case you are curious, the heatmap was generated using Seaborn's heatmap function (http://seaborn.pydata.org/generated/seaborn.heatmap.html) and the following line of code, where df.corr() computes the pairwise correlation between columns:

sns.heatmap(df.corr(), square=True, cmap='RdYlGn')

Once you have a feel for the data, consider the statements below and select the one that is not true. After this, Hugo will explain the mechanics of linear regression in the next video and you will be on your way building regression models!

## Fit & predict for regression

Now, you will fit a linear regression and predict life expectancy using just one feature. You saw Andy do this earlier using the 'RM' feature of the Boston housing dataset. In this exercise, you will use the 'fertility' feature of the Gapminder dataset. 

**Since the goal is to predict life expectancy, the target variable here is 'life'.** 

The array for the target variable has been pre-loaded as y and the array for 'fertility' has been pre-loaded as X_fertility.

A scatter plot with 'fertility' on the x-axis and 'life' on the y-axis has been generated. As you can see, there is a strongly negative correlation, so a linear regression should be able to capture this trend. Your job is to fit a linear regression and then predict the life expectancy, overlaying these predicted values on the plot to generate a regression line. You will also compute and print the R2
score using sckit-learn's .score() method.

In [ ]:
# Import LinearRegression
from sklearn.linear_model import LinearRegression

# Create the regressor: reg
reg = linear_model.LinearRegression()


y.shape
# Out[5]: (139, 1)

y
# Out[6]: 
# array([[ 75.3],
#        [ 58.3],
#        [ 75.5],
#        [ 72.5],
#          ...
#        [ 68.7],
#        [ 75.4],
#        [ 52. ],
#        [ 49. ]])

X.shape
#Out[8]: (139, 8)

X
#       population  fertility    HIV        CO2  BMI_male      GDP  BMI_female   child_mortality
# 0     34811059.0       2.73   0.10   3.328945  24.59620  12314.0    129.9049   29.5
# 1     19842251.0       6.43   2.00   1.474353  22.25083   7103.0    130.1247   192.0
# 2     40381860.0       2.24   0.50   4.785170  27.50170  14646.0    118.8915   15.4
# [139 rows x 8 columns]

X_fertility
# Out[15]: 
# array([[ 2.73],
#        [ 6.43],
#        [ 2.24],
#        [ 1.4 ],
#         ...
#        [ 1.86],
#        [ 5.88],
#        [ 3.85]])

# Create the prediction space
prediction_space = np.linspace(min(X_fertility), max(X_fertility)).reshape(-1,1)

min(X_fertility)
# Out[16]: array([ 1.28])

max(X_fertility)
# Out[17]: array([ 7.59])

np.linspace(min(X_fertility), max(X_fertility)).reshape(-1,1)
# Out[14]: 
# array([[ 1.28 ], 
#        [1.40877551], 
#        [1.53755102], 
#        [1.66632653], 
#         ... 
#        [7.20367347], 
#        [7.33244898], 
#        [7.46122449],
#        [7.59]])

# Fit the model to the data
reg.fit(X_fertility, y)

# Compute predictions over the prediction space: y_pred
y_pred = reg.predict(prediction_space)

# Print R^2 
print(reg.score(X_fertility, y))
# <script.py> output:
#   0.619244216774

# Plot regression line
plt.plot(prediction_space, y_pred, color='black', linewidth=3)
plt.show()

In [1]:
import numpy as np

In [8]:
np.arange(1.28, 7.59)

array([1.28, 2.28, 3.28, 4.28, 5.28, 6.28, 7.28])

In [9]:
np.linspace(1.28, 7.59,retstep=True)

(array([1.28      , 1.40877551, 1.53755102, 1.66632653, 1.79510204,
        1.92387755, 2.05265306, 2.18142857, 2.31020408, 2.43897959,
        2.5677551 , 2.69653061, 2.82530612, 2.95408163, 3.08285714,
        3.21163265, 3.34040816, 3.46918367, 3.59795918, 3.72673469,
        3.8555102 , 3.98428571, 4.11306122, 4.24183673, 4.37061224,
        4.49938776, 4.62816327, 4.75693878, 4.88571429, 5.0144898 ,
        5.14326531, 5.27204082, 5.40081633, 5.52959184, 5.65836735,
        5.78714286, 5.91591837, 6.04469388, 6.17346939, 6.3022449 ,
        6.43102041, 6.55979592, 6.68857143, 6.81734694, 6.94612245,
        7.07489796, 7.20367347, 7.33244898, 7.46122449, 7.59      ]),
 0.12877551020408162)

## Train/test split for regression

As you learned in Chapter 1, train and test sets are vital to ensure that your supervised learning model is able to generalize well to new data. This was true for classification models, and is equally true for linear regression models.

In this exercise, you will split the Gapminder dataset into training and testing sets, and then fit and predict a linear regression over all features. In addition to computing the R2
score, you will also compute the Root Mean Squared Error (RMSE), which is another commonly used metric to evaluate regression models. The feature array X and target variable array y have been pre-loaded for you from the DataFrame df.

In [ ]:
# Import necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

X_train.shape
# Out[3]: (97, 8)

# Out[12]: 
# array([[  1.33994100e+06,   1.62000000e+00,   1.20000000e+00,
#           1.30313789e+01,   2.62644600e+01,   2.47430000e+04,
#           1.29516100e+02,   5.50000000e+00], ...
#        [  3.85257520e+07,   1.33000000e+00,   1.00000000e-01,
#           8.27076715e+00,   2.66738000e+01,   1.99960000e+04,
#           1.29676500e+02,   6.70000000e+00]])

y_train.shape
# Out[4]: (97,)

y_train
# Out[11]: 
# array([ 74. ,  54.8,  75.5,  74.1,  52. , ...
#         49. ,  57.4,  61. ,  67.6,  67.6,  59.7,  75.3])

X_test.shape
# Out[5]: (42, 8)

X_test
# Out[9]: 
# array([[  2.69527190e+07,   2.46000000e+00,   1.00000000e-01,
#           4.47666902e+00,   2.53205400e+01,   3.73300000e+03,
#           1.24346200e+02,   4.92000000e+01],

y_test.shape
# Out[6]: (42,)

y_test
# Out[8]: 
# array([ 68.7,  66.1,  76.5,  67.4,  79.4,  70.7,  58.3,  72.3,  60. ,
#         70.9,  74.8,  57.2,  63.6,  59.4,  55. ,  77.6,  79.4,  62.6,
#         76. ,  76.4,  70.1,  74.3,  55.8,  81.5,  80.7,  75.1,  79.5,
#         76.9,  61.2,  73.2,  70.1,  73.8,  80.4,  82.6,  73.4,  62.2,
#         72.1,  80.3,  74.6,  75.3,  58. ,  58.6])

# Create the regressor: reg_all
reg_all = LinearRegression()

# Fit the regressor to the training data
reg_all.fit(X_train, y_train)

# Predict on the test data: y_pred
y_pred = reg_all.predict(X_test)

# Compute and print R^2 and RMSE
print("R^2: {}".format(reg_all.score(X_test, y_test)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

# R^2: 0.838046873142936
# Root Mean Squared Error: 3.2476010800377213

Using all features has improved the model score. This makes sense, as the model has more information to learn from. 

However, there is one potential pitfall to this process. Can you spot it? 

## Cross-Validation: CV

## 5-fold Cross-Validation (CV)

Cross-validation is a vital step in evaluating a model. It maximizes the amount of data that is used to train the model, as during the course of training, the model is not only trained, but also tested on all of the available data.

In this exercise, you will practice 5-fold cross validation on the Gapminder data. By default, scikit-learn's cross_val_score() function uses R2

as the metric of choice for regression. Since you are performing 5-fold cross-validation, the function will return 5 scores. Your job is to compute these 5 scores and then take their average.

The DataFrame has been loaded as df and split into the feature/target variable arrays X and y. The modules pandas and numpy have been imported as pd and np, respectively.

In [ ]:
# Import the necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create a linear regression object: reg
reg = LinearRegression()

# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(reg, X, y, cv=5)

# Print the 5-fold cross-validation scores
print(cv_scores)
[ 0.81720569  0.82917058  0.90214134  0.80633989  0.94495637]
print("Average 5-Fold CV Score: {}".format(np.mean(cv_scores)))
Average 5-Fold CV Score: 0.8599627722793232

## K-Fold CV comparison

Cross validation is essential but do not forget that the more folds you use, the more computationally expensive cross-validation becomes. In this exercise, you will explore this for yourself. Your job is to perform 3-fold cross-validation and then 10-fold cross-validation on the Gapminder dataset.

In the IPython Shell, you can use %timeit to see how long each 3-fold CV takes compared to 10-fold CV by executing the following cv=3 and cv=10:

%timeit cross_val_score(reg, X, y, cv = ____)

pandas and numpy are available in the workspace as pd and np. The DataFrame has been loaded as df and the feature/target variable arrays X and y have been created.

In [ ]:
# Import necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create a linear regression object: reg
reg = LinearRegression()

# Perform 3-fold CV
cvscores_3 = cross_val_score(reg, X, y, cv = 3)
print(np.mean(cvscores_3))
# 0.843612862013
    
# Perform 10-fold CV
cvscores_10 = cross_val_score(reg, X, y, cv = 10)
print(np.mean(cvscores_10))
# 0.843612862013

# Regularization I: Lasso

In the video, you saw how Lasso selected out the 'RM' feature as being the most important for predicting Boston house prices, while shrinking the coefficients of certain other features to 0. Its ability to perform feature selection in this way becomes even more useful when you are dealing with data involving thousands of features.

In this exercise, you will fit a lasso regression to the Gapminder data you have been working with and plot the coefficients. Just as with the Boston data, you will find that the coefficients of some features are shrunk to 0, with only the most important ones remaining.

The feature and target variable arrays have been pre-loaded as X and y.

In [ ]:
# Import Lasso
from sklearn.linear_model import Lasso

# Instantiate a lasso regressor: lasso
lasso = Lasso(alpha=0.4, normalize=True)

# Fit the regressor to the data
lasso.fit(X, y)

# Compute and print the coefficients
lasso_coef = lasso.coef_
print(lasso_coef)

# Plot the coefficients
plt.plot(range(len(df_columns)), lasso_coef)
plt.xticks(range(len(df_columns)), df_columns.values, rotation=60)
plt.margins(0.02)
plt.show()

# [-0.         -0.         -0.          0.          0.          0.         -0.   -0.07087587]

# According to the lasso algorithm, it seems like 'child_mortality' is the most important feature 
#   when predicting life expectancy.

## Regularization II: Ridge

**Lasso is great for feature selection, but when building regression models, Ridge regression should be your first choice.**

Recall that lasso performs regularization by adding to the loss function a penalty term of the absolute value of each coefficient multiplied by some alpha. This is also known as L1
regularization because the regularization term is the L1 norm of the coefficients. This is not the only way to regularize, however.

If instead you took the sum of the squared values of the coefficients multiplied by some alpha (like in Ridge regression) you would be computing the L2 norm. 

In this exercise, you will practice fitting ridge regression models over a range of different alphas, and plot cross-validated R2 scores for each, using this function that we have defined for you, which plots the R2 score as well as standard error for each alpha:

def display_plot(cv_scores, cv_scores_std):
    
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    ax.plot(alpha_space, cv_scores)

    std_error = cv_scores_std / np.sqrt(10)

    ax.fill_between(alpha_space, cv_scores + std_error, cv_scores - std_error, alpha=0.2)
    ax.set_ylabel('CV Score +/- Std Error')
    ax.set_xlabel('Alpha')
    ax.axhline(np.max(cv_scores), linestyle='--', color='.5')
    ax.set_xlim([alpha_space[0], alpha_space[-1]])
    ax.set_xscale('log')
    plt.show()
    
Don't worry about the specifics of the above function works. The motivation behind this exercise is for you to see how the R2 score varies with different alphas, and to understand the importance of selecting the right value for alpha. You'll learn how to tune alpha in the next chapter.

In [ ]:
X
# Out[1]: 
# array([[  3.48110590e+07,   2.73000000e+00,   1.00000000e-01, ...,
#           1.23140000e+04,   1.29904900e+02,   2.95000000e+01], 
#       [  1.31145790e+07,   5.88000000e+00,   1.36000000e+01, ...,
#          3.03900000e+03,   1.32449300e+02,   9.49000000e+01],
#       [  1.34954620e+07,   3.85000000e+00,   1.51000000e+01, ...,
#          1.28600000e+03,   1.31974500e+02,   9.83000000e+01]])

# y
# Out[2]: 
# array([ 75.3,  58.3,  75.5,  72.5,  81.5,  80.4,  70.6,  72.2,  68.4,
#         75.3,  70.1,  79.4,  70.7,  63.2,  67.6,  70.9,  61.2,  73.9, ...
#         60. ,  71.3,  76.5,  75.1,  57.2,  68.2,  79.5,  78.2,  76. ,
#         68.7,  75.4,  52. ,  49. ])

# np.logspace(-4, 0, 50)
# Out[6]: 
# array([  1.00000000e-04,   1.20679264e-04,   1.45634848e-04,
#          1.75751062e-04,   2.12095089e-04,   2.55954792e-04,
#          3.08884360e-04,   3.72759372e-04,   4.49843267e-04, ...
#          2.68269580e-01,   3.23745754e-01,   3.90693994e-01,
#          4.71486636e-01,   5.68986603e-01,   6.86648845e-01,
#          8.28642773e-01,   1.00000000e+00])

# Import necessary modules
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

# Setup the array of alphas and lists to store scores
alpha_space = np.logspace(-4, 0, 50)
ridge_scores = []
ridge_scores_std = []

# Create a ridge regressor: ridge
ridge = Ridge(normalize=True)

# Compute scores over range of alphas
for alpha in alpha_space:

    # Specify the alpha value to use: ridge.alpha
    ridge.alpha = alpha
    print(alpha)
    # Perform 10-fold CV: ridge_cv_scores
    ridge_cv_scores = cross_val_score(ridge, X, y, cv=10)
    
    # Append the mean of ridge_cv_scores to ridge_scores
    ridge_scores.append(np.mean(ridge_cv_scores))
    
    # Append the std of ridge_cv_scores to ridge_scores_std
    ridge_scores_std.append(np.std(ridge_cv_scores))

# Display the plot
display_plot(ridge_scores, ridge_scores_std)

print(alpha)
output:
    0.0001
    0.000120679264064
    0.00014563484775
    0.000175751062485
    0.000212095088792
    0.00025595479227
    0.000308884359648
    0.000372759372031
    0.000449843266897
    0.000542867543932
    0.00065512855686
    0.000790604321091
    0.00095409547635
    0.00115139539933
    0.00138949549437
    0.00167683293681
    0.00202358964773
    0.00244205309455
    0.00294705170255
    0.00355648030622
    0.00429193426013
    0.00517947467923
    0.00625055192527
    0.00754312006335
    0.00910298177992
    0.0109854114199
    0.0132571136559
    0.0159985871961
    0.0193069772888
    0.0232995181052
    0.0281176869797
    0.033932217719
    0.0409491506238
    0.0494171336132
    0.0596362331659
    0.0719685673001
    0.0868511373751
    0.104811313415
    0.126485521686
    0.152641796718
    0.184206996933
    0.222299648253
    0.268269579528
    0.323745754282
    0.390693993705
    0.471486636346
    0.568986602902
    0.686648845004
    0.828642772855
    1.0