## Data Camp: Intro to Python - Course 1

## Addition and Subtraction

In [1]:
# Addition and subtraction
print(5 + 5)
print(5 - 5)

# Multiplication and division
print(3 * 5)
print(10 / 2)

# Exponentiation
print(4 ** 2)

# Modulo
print(18 % 7)

# How much is your $100 worth after 7 years?

print(100 * 1.1 ** 7)
print(100 * 1.1 * 1.1 * 1.1 * 1.1 * 1.1 * 1.1 * 1.1 )

10
0
15
5
16
4
194.87171
194.87171


## Variables 

In [3]:
# Several variables to experiment with
savings = 100
factor = 1.1
desc = "compound interest"

# Assign product of factor and savings to year1
year1 = savings * factor

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)

<type 'float'>
compound interestcompound interest


In [4]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171. Awesome!


In [5]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [6]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<type 'list'>


## Creating Lists 

In [9]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print("The first element in the list [1]: " + str(areas[1])) # Must convert float to str, must concatenate like elements

# Print out last element from areas
print("The last element in the list [-1]: " + str(areas[-1]))  # Must convert float to str, must concatenate like elements

# Print out the area of the living room
print(areas[5])

The first element in the list [1]: 11.25
The last element in the list [-1]: 9.5
20.0


In [15]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

# Print the variable type of eat_sleep_area
print("The variable eat_sleep_area is of type: " + str(type(eat_sleep_area)))

28.75
The variable eat_sleep_area is of type: <type 'float'>


In [20]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:10]
 
# Print out downstairs and upstairs
print("Using [:6] which begins at position 0 and excludes the 6th position:")
print(downstairs)
print("Using [6:10] which begins at position 6 and excludes the 10th position:")
print(upstairs)

Using [:6] which begins at position 0 and excludes the 6th position:
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
Using [6:10] which begins at position 6 and excludes the 10th position:
['bedroom', 10.75, 'bathroom', 9.5]


## Replacing Elements Within a List 

In [21]:
#Replace List Elements

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
print("The area of the bathroom pre change: " + str(areas[-1]))
areas[-1] = 10.5
print("The area of the bathroom post change: " + str(areas[-1]))
# Change "living room" to "chill zone"
areas[4] = "chill zone"

The area of the bathroom pre change: 9.5
The area of the bathroom post change: 10.5


## Extending a List 

In [10]:
# Extend a list
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas[:] + ["poolhouse", 24.5]
print(areas)
print(areas_1)
# Add garage data to areas_1, new list is areas_2

areas_2 = areas_1[:] + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


## Deleting elements within a List 

In [11]:
# Delete list elements
del(areas_1[-1])
print(areas_1)
del(areas_2[-4:-1])
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse']
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 15.45]


In [13]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)
print(areas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


In [1]:
# Familiar functions

# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<type 'list'>
4


In [5]:
# Multiple arguments

# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full

full = first + second
print("Adding two lists together merely concatenates the two lists: " + str(full))

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

Adding two lists together merely concatenates the two lists: [11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


In [23]:
# Methods: Functions that belong to objects

sister = "Liz" # Str object - Methods: capitalize(), replace()

height = 1.73  # float object - Methods: bit_length(), conjugate()

fam = ["Liz", 1.73, "Emma", 1.68, "Mom", 1.73, "Dad", 1.89]  # list Object - Methods: index(), count()

# Calling Methods on an object by first indicating the object then the medthod name, preceded by a "dot"

fam.index("Mom")

# count(), counts the number of occurances in a list

fam.count(1.73)

# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up
room_up = room.upper()

# Print out room and room_up
print(room)
print(room_up)

# Print out the number of o's in room
print(room.count('o'))

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(14.5))

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

poolhouse
POOLHOUSE
3
2
0
[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [32]:
# Installing Packages

# https://pip.readthedocs.io/en/stable/installing/

# Download PIP
# python2 get-pip.py
# pip2 install numpy

# import numphy as np

# np.array([1, 2, 3])

# from numphy import array

In [27]:
# Import package

# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*pow(r,2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.70176968209
Area: 0.580880481649


In [28]:
# Selective import

# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.1057211


In [39]:
# NumPy Numeric Python

# Alternatie to Python List is NumPy Array which will calculations over the entire array using element-wise calculations

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

print(np_baseball)

# height is available as a regular list

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2 

# Print out bmi
print(bmi)


<type 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]
1.73
0.043941999999999995


NameError: name 'weight' is not defined

In [57]:
x = [4 , 9 , 6, 3, 1]
print("Python list have commas seperating the elements within the list: " + str(x))
print("The second element withing the Python list is: " + str(x[1]))
import numpy as np
y = np.array(x)
print("In a NumPy array the elements are NOT seperated by commas: " + str(y))
print(type(y))

high = y > 5
print("All elements in the NumPy array evaluate for being greater than 5 are: " + str(high))

print("The Elements, in terms of values, within the NumPy array that are greater than 5 are: " + str(y[y>5]))

Python list have commas seperating the elements within the list: [4, 9, 6, 3, 1]
The second element withing the Python list is: 9
In a NumPy array the elements are NOT seperated by commas: [4 9 6 3 1]
<type 'numpy.ndarray'>
All elements in the NumPy array evaluate for being greater than 5 are: [False  True  True False False]
The Elements, in terms of values, within the NumPy array that are greater than 5 are: [9 6]


In [59]:
# NumPy Side Effects

# NumPy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types 
#  are changed to end up with a homogeneous list. This is known as type coercion.

# Typical arithmetic operators, such as +, -, * and / have a different meanings

print(np.array([4, 3, 0, 12, 9, 4, 8, 23, 12, 16, 21]) + np.array([14, 3, 0, 22, 9, 7, 8, 43, 1, 6, 11]))


[18  6  0 34 18 11 16 66 13 22 32]


In [62]:
# Subsetting NumPy Arrays

x = np.array([4, 3, 0, 12, 9, 4, 8, 23, 12, 16, 21, 14, 3, 0, 22, 9, 7, 8, 43, 1, 6, 11])

print(x)
print(type(x)) #ndarray means N-Diemensional Array 
print(x[4:11])

[ 4  3  0 12  9  4  8 23 12 16 21 14  3  0 22  9  7  8 43  1  6 11]
<type 'numpy.ndarray'>
[ 9  4  8 23 12 16 21]


In [82]:
# 2D NumPy Array
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d


np_2d.shape

# Accomplish the same output
np_2d[0][1]
np_2d[0, 1]

# To get the second and third column of both rows:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [2]:
# NumPy: Basic Statistics

np_2d = np.array([[1.73, 1.68], [1.71, 1.89], [65.4, 59.2], [63.6, 88.4]])

print("The np.mean of the first column in all or the observations is: " + str(np.mean(np_2d[:,0])))
print("The np.median of the first column in all or the observations is: " + str(np.median(np_2d[:,0])))

corr = np.corrcoef(np_2d[:,0], np_2d[:,1])
print("Correlation: " + str(corr))

# Simulated Values
# np.random.normal(Distribution Mean, Distribution S.D., Number of Samples)
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

np_city = np.column_stack((height, weight))

NameError: name 'np' is not defined

In [8]:
# Blend it all together
import numpy as np
positions = ['GK', 'M', 'A', 'D', 'GK', 'M', 'A', 'D','GK', 'M', 'A', 'D','GK', 'M', 'A', 'D','GK', 'M', 'A', 'D']
heights = [191.8, 184, 185, 180, 195.7, 174, 175, 170, 196.6, 182, 183, 178, 198.9, 181, 182, 176, 200.9, 180, 180, 180]
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
print("The heights of all of the Goal Keepers are: " + str(np_heights[np_positions == 'GK']))
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

The heights of all of the Goal Keepers are: [191 195 196 198 200]
Median height of goalkeepers: 196.0
Median height of other players: 180.0
